
package ec.edu.espe.evsustore.view;

import ec.edu.espe.evsustore.controller.CatalogController;
import ec.edu.espe.evsustore.controller.SaleController;
import ec.edu.espe.evsustore.controller.TransactionsController;
import ec.edu.espe.evsustore.model.Customer;
import ec.edu.espe.evsustore.model.Sale;
import ec.edu.espe.evsustore.utils.DecimalsControl;
import ec.edu.espe.evsustore.utils.Tax;
import ec.edu.espe.evsustore.utils.ViewManager;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JRadioButton;

/**
 *
 * @author Joan Cobeña, KillChain, DCCO-ESPE
 */
public class PnelPayConfirmation extends javax.swing.JPanel {

    SaleController saleController = SaleController.getInstance();
    CatalogController catalogController = CatalogController.getInstance();
    
    Customer customer;
    ArrayList<HashMap<Object, Object>> orderedProducts;
    
    /**
     * Creates new form PnelPayConfirmation
     * @param customer
     * @param orderedProducts
     */
    public PnelPayConfirmation(Customer customer, ArrayList<HashMap<Object, Object>> orderedProducts) {
        this.customer = customer;
        this.orderedProducts = orderedProducts;
        
        initComponents();
        addListeners();
        fillFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupPayMethod = new javax.swing.ButtonGroup();
        pnelContent = new javax.swing.JPanel();
        pnelView = new javax.swing.JPanel();
        pnelCustomerInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtIdCardNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pnelSaleInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProductsResume = new javax.swing.JTextArea();
        pnelSubtotalAndTotal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSubtotal12 = new javax.swing.JTextField();
        txtSubtotal0 = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        txtICE = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        pnelPayMethods = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnCash = new javax.swing.JRadioButton();
        btnBankTransfer = new javax.swing.JRadioButton();
        btnPaypal = new javax.swing.JRadioButton();
        pnelButtons = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnConfirmPay = new javax.swing.JButton();

        setEnabled(false);

        jLabel1.setText("Información del cliente:");

        jLabel2.setText("Nombres y Apellidos:");

        jLabel3.setText("N° de Cédula:");

        txtName.setEditable(false);
        txtName.setEnabled(false);
        txtName.setOpaque(false);

        txtIdCardNumber.setEditable(false);
        txtIdCardNumber.setEnabled(false);
        txtIdCardNumber.setOpaque(false);

        jLabel4.setText("Dirección:");

        txtLocation.setEditable(false);
        txtLocation.setEnabled(false);
        txtLocation.setOpaque(false);

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Email:");

        txtPhoneNumber.setEditable(false);
        txtPhoneNumber.setEnabled(false);
        txtPhoneNumber.setOpaque(false);

        txtEmail.setEditable(false);
        txtEmail.setEnabled(false);
        txtEmail.setOpaque(false);

        javax.swing.GroupLayout pnelCustomerInfoLayout = new javax.swing.GroupLayout(pnelCustomerInfo);
        pnelCustomerInfo.setLayout(pnelCustomerInfoLayout);
        pnelCustomerInfoLayout.setHorizontalGroup(
            pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCardNumber))
                    .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtLocation))
                    .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhoneNumber))
                    .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnelCustomerInfoLayout.setVerticalGroup(
            pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        txtProductsResume.setEditable(false);
        txtProductsResume.setColumns(20);
        txtProductsResume.setRows(5);
        txtProductsResume.setEnabled(false);
        txtProductsResume.setOpaque(false);
        jScrollPane1.setViewportView(txtProductsResume);

        javax.swing.GroupLayout pnelSaleInfoLayout = new javax.swing.GroupLayout(pnelSaleInfo);
        pnelSaleInfo.setLayout(pnelSaleInfoLayout);
        pnelSaleInfoLayout.setHorizontalGroup(
            pnelSaleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelSaleInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnelSaleInfoLayout.setVerticalGroup(
            pnelSaleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelSaleInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel7.setText("Subtotal (12%):");

        jLabel8.setText("Subtotal(0%):");

        jLabel9.setText("IVA:");

        jLabel10.setText("ICE:");

        jLabel11.setText("TOTAL:");

        txtSubtotal12.setEditable(false);
        txtSubtotal12.setEnabled(false);
        txtSubtotal12.setOpaque(false);

        txtSubtotal0.setEditable(false);
        txtSubtotal0.setEnabled(false);
        txtSubtotal0.setOpaque(false);

        txtIVA.setEditable(false);
        txtIVA.setEnabled(false);
        txtIVA.setOpaque(false);

        txtICE.setEditable(false);
        txtICE.setEnabled(false);
        txtICE.setOpaque(false);

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);
        txtTotal.setOpaque(false);

        javax.swing.GroupLayout pnelSubtotalAndTotalLayout = new javax.swing.GroupLayout(pnelSubtotalAndTotal);
        pnelSubtotalAndTotal.setLayout(pnelSubtotalAndTotalLayout);
        pnelSubtotalAndTotalLayout.setHorizontalGroup(
            pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelSubtotalAndTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtICE)
                    .addComponent(txtIVA)
                    .addComponent(txtSubtotal0)
                    .addComponent(txtSubtotal12))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        pnelSubtotalAndTotalLayout.setVerticalGroup(
            pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelSubtotalAndTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSubtotal12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSubtotal0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnelSubtotalAndTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Método de Pago:");

        btnGroupPayMethod.add(btnCash);
        btnCash.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCash.setText("Efectivo");

        btnGroupPayMethod.add(btnBankTransfer);
        btnBankTransfer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnBankTransfer.setText("Transferencia Bancaria");
        btnBankTransfer.setEnabled(false);

        btnGroupPayMethod.add(btnPaypal);
        btnPaypal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPaypal.setText("Paypal");
        btnPaypal.setEnabled(false);

        javax.swing.GroupLayout pnelPayMethodsLayout = new javax.swing.GroupLayout(pnelPayMethods);
        pnelPayMethods.setLayout(pnelPayMethodsLayout);
        pnelPayMethodsLayout.setHorizontalGroup(
            pnelPayMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPayMethodsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnelPayMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPayMethodsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(pnelPayMethodsLayout.createSequentialGroup()
                        .addGroup(pnelPayMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCash)
                            .addComponent(btnBankTransfer)
                            .addComponent(btnPaypal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnelPayMethodsLayout.setVerticalGroup(
            pnelPayMethodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPayMethodsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBankTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaypal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnConfirmPay.setText("Proceder con el Pago");
        btnConfirmPay.setEnabled(false);
        btnConfirmPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnelButtonsLayout = new javax.swing.GroupLayout(pnelButtons);
        pnelButtons.setLayout(pnelButtonsLayout);
        pnelButtonsLayout.setHorizontalGroup(
            pnelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                .addComponent(btnConfirmPay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnelButtonsLayout.setVerticalGroup(
            pnelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelButtonsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmPay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnelViewLayout = new javax.swing.GroupLayout(pnelView);
        pnelView.setLayout(pnelViewLayout);
        pnelViewLayout.setHorizontalGroup(
            pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelViewLayout.createSequentialGroup()
                .addGroup(pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelViewLayout.createSequentialGroup()
                        .addGroup(pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelViewLayout.createSequentialGroup()
                                .addComponent(pnelSaleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelViewLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pnelSubtotalAndTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGroup(pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnelPayMethods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnelCustomerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnelViewLayout.setVerticalGroup(
            pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelViewLayout.createSequentialGroup()
                .addGroup(pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnelViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnelCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnelSaleInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnelPayMethods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnelSubtotalAndTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnelContentLayout = new javax.swing.GroupLayout(pnelContent);
        pnelContent.setLayout(pnelContentLayout);
        pnelContentLayout.setHorizontalGroup(
            pnelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnelContentLayout.setVerticalGroup(
            pnelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmPayActionPerformed
        Sale confirmedSale = confirmSale();
        if(btnGroupPayMethod.getSelection() == btnCash.getModel()){
            PnelCashPay pnelCashPay = new PnelCashPay(confirmedSale);
            ViewManager.showPanel(pnelContent, pnelCashPay);
        }
        else if(btnGroupPayMethod.getSelection() == btnBankTransfer.getModel()){
            // TODO Bank Transfer Verification
        }
        else if(btnGroupPayMethod.getSelection() == btnPaypal.getModel()){
            //TODO PayPal Verification
        }
    }//GEN-LAST:event_btnConfirmPayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void addListeners(){
        ArrayList<JRadioButton> buttons = new ArrayList<>();
        buttons.add(btnCash);
        buttons.add(btnPaypal);
        buttons.add(btnBankTransfer);
        ButtonGroupListener btnListener = new ButtonGroupListener(buttons, btnConfirmPay);
        
        btnCash.addActionListener(btnListener);
        btnPaypal.addActionListener(btnListener);
        btnBankTransfer.addActionListener(btnListener);
    }
    
    private Sale confirmSale(){
        Double total = Double.parseDouble(txtTotal.getText().toString());
        
        Sale sale = new Sale(saleController.generateId(), catalogController.convertAllIntoCatalogProducts(orderedProducts), customer, total, LocalDate.now());
        return sale;
    }
    
    private void fillFields(){
        String productsResume = " Cantidad \t||\t Descripción \t||\t Precio por unidad ";
        Double Subtotal12 = 0.0;

        for (HashMap map : orderedProducts) {
            String txtPrice = map.get("price").toString();
            String txtQuantity = map.get("quantity").toString();
            String txtDescription = map.get("productDescription").toString();

            Subtotal12 = Subtotal12 + TransactionsController.calcTotal(map);
            productsResume = productsResume + " \n " + txtQuantity + " \t||\t " + txtDescription + " \t||\t " + txtPrice;
        }

        txtProductsResume.setText(productsResume);

        txtSubtotal12.setText(Subtotal12.toString());
        txtSubtotal0.setText("0.0");
        Double IVA = Tax.computeIVA(Subtotal12, 12.0);
        txtIVA.setText(String.format("%.2f", IVA));
        txtICE.setText("0.0");
        Double Total = Subtotal12 + IVA;

        
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.US);
        DecimalFormat decimalFormat = new DecimalFormat("0.00", symbols);
        String formattedTotal = decimalFormat.format(DecimalsControl.roundToTwoTenths(Total));

        if(formattedTotal.contains(",")){
            formattedTotal = formattedTotal.replace(",", ".");
        }
        
        txtTotal.setText(formattedTotal);

        txtName.setText(customer.getName() + " " + customer.getLastName());
        txtIdCardNumber.setText(customer.getIdCardNumber());
        txtLocation.setText(customer.getLocation());
        txtPhoneNumber.setText(customer.getPhoneNumber());
        txtEmail.setText(customer.getEmail());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnBankTransfer;
    private javax.swing.JRadioButton btnCash;
    private javax.swing.JButton btnConfirmPay;
    private javax.swing.ButtonGroup btnGroupPayMethod;
    private javax.swing.JRadioButton btnPaypal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnelButtons;
    private javax.swing.JPanel pnelContent;
    private javax.swing.JPanel pnelCustomerInfo;
    private javax.swing.JPanel pnelPayMethods;
    private javax.swing.JPanel pnelSaleInfo;
    private javax.swing.JPanel pnelSubtotalAndTotal;
    private javax.swing.JPanel pnelView;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtICE;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtIdCardNumber;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextArea txtProductsResume;
    private javax.swing.JTextField txtSubtotal0;
    private javax.swing.JTextField txtSubtotal12;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
