
package ec.edu.espe.evsustore.view;

import ec.edu.espe.evsustore.controller.HardwareComponentController;
import ec.edu.espe.evsustore.controller.ViewController;
import ec.edu.espe.evsustore.model.HardwareComponent;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Andres Espin, KillChain, DCOO-ESPE
 */
public class PnelHardwareComponent extends javax.swing.JPanel {

    /**
     * Creates new form PnelHardwareComponent
     */
    public PnelHardwareComponent() {
        initComponents();
        
        int generatedId = HardwareComponentController.generateId();
        txtId.setText(String.valueOf(generatedId));
        
        btnClear.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {

                    clearFields();

                }
            }
        );
        
        txtCost.addKeyListener(doubleListener());
        txtPrice.addKeyListener(doubleListener());
        txtName.addKeyListener(alphabeticListener());
    }
    
    public PnelHardwareComponent(HardwareComponent updatingComponent) {
        initComponents();
        
        fillFields(updatingComponent);
        
        int idOfUpdating = updatingComponent.getId();
        
        btnClear.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {

                    clearFields(idOfUpdating);

                }
            }
        );
        
        txtCost.addKeyListener(doubleListener());
        txtPrice.addKeyListener(doubleListener());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();
        btnSave5 = new javax.swing.JButton();
        btnClear5 = new javax.swing.JButton();
        btnBackToMainMenu5 = new javax.swing.JButton();

        Content.setBackground(new java.awt.Color(18, 9, 24));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(169, 104, 216));
        txtId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(133, 44, 194));
        txtId.setEnabled(false);

        txtQuantity.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(133, 44, 194));

        txtName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(133, 44, 194));

        txtModel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtModel.setForeground(new java.awt.Color(133, 44, 194));
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtCost.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCost.setForeground(new java.awt.Color(133, 44, 194));

        txtPrice.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(133, 44, 194));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("COMPONENTE DE HARDWARE");

        btnUploadImage.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnUploadImage.setText("Subir imagen...");

        btnSave5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnSave5.setText("Guardar Cambios");
        btnSave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtQuantity)
                                    .addComponent(txtModel)
                                    .addComponent(txtCost)
                                    .addComponent(txtPrice))
                                .addGap(68, 68, 68)
                                .addComponent(btnUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSave5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel8)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8))
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUploadImage))))
                .addGap(25, 25, 25)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnSave5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        btnClear5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnClear5.setText("Vaciar Campos");
        btnClear5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear5ActionPerformed(evt);
            }
        });

        btnBackToMainMenu5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnBackToMainMenu5.setText("Volver al Menú Anterior");
        btnBackToMainMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainMenu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnClear5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackToMainMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToMainMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnSave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave5ActionPerformed
        HardwareComponent enteredComponent = readComponent();

        String warningMessage = "¿Está seguro de que quiere guardar el siguiente producto?\n";
        String component = enteredComponent.toString().replace("\t|| ", "\n");

        int option = JOptionPane.showConfirmDialog(getRootPane(), warningMessage + component);

        if (option == 0) {
            ViewController.saveComponentInDB(enteredComponent);
            JOptionPane.showMessageDialog(getRootPane(), "Se ha guardado exitosamente");
            clearFields();

        } else if (option == 1) {
            JOptionPane.showMessageDialog(getRootPane(), "No guardado");
            clearFields();
        } else {

        }
    }//GEN-LAST:event_btnSave5ActionPerformed

    private void btnClear5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear5ActionPerformed
        //
    }//GEN-LAST:event_btnClear5ActionPerformed

    private void btnBackToMainMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainMenu5ActionPerformed
        PnelInventory pnelInventory=new PnelInventory();
        showPanel(pnelInventory);
    }//GEN-LAST:event_btnBackToMainMenu5ActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton btnBackToMainMenu;
    private javax.swing.JButton btnBackToMainMenu1;
    private javax.swing.JButton btnBackToMainMenu2;
    private javax.swing.JButton btnBackToMainMenu3;
    private javax.swing.JButton btnBackToMainMenu4;
    private javax.swing.JButton btnBackToMainMenu5;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnClear4;
    private javax.swing.JButton btnClear5;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSave3;
    private javax.swing.JButton btnSave4;
    private javax.swing.JButton btnSave5;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnelButtons;
    private javax.swing.JPanel pnelButtons1;
    private javax.swing.JPanel pnelButtons2;
    private javax.swing.JPanel pnelButtons3;
    private javax.swing.JPanel pnelButtons4;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
    private KeyListener doubleListener (){
        KeyListener doubleKeyListener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                validateTypedDoubleNumbers(e);
            }

            @Override
            public void keyPressed(KeyEvent e) {
            
            }

            @Override
            public void keyReleased(KeyEvent e) {
             
            }
        };
        return doubleKeyListener;
    }
    
    private KeyListener alphabeticListener (){
        KeyListener alphabeticKeyListener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                validateTypedCharacters(e);
            }

            @Override
            public void keyPressed(KeyEvent e) {
              
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        };
        return alphabeticKeyListener;
    }
    
    private void validateTypedCharacters (java.awt.event.KeyEvent evt) { 
        char enteredChar = evt.getKeyChar ();  
        if (!Character.toString (enteredChar).matches ("[a-zA-ZáéíóúÁÉÍÓÚñÑ]")){
            evt.consume ();
        } 
    }
    
    private void validateTypedDoubleNumbers (java.awt.event.KeyEvent evt) { 
        
        char enteredChar = evt.getKeyChar ();
        if (!Character.toString (enteredChar).matches ("[0-9\\.]")) {
            evt.consume ();
        }
        else {
            JTextField field = (JTextField) evt.getSource ();
            String numbersText = field.getText ();
            if(numbersText!=null){
                if (numbersText.matches ("[0-9]+((\\.){1}[0-9]{2})")) {
                    evt.consume ();
                }
            }
            
        }
    }
    
    private HardwareComponent readComponent() {                                          
        int id = Integer.parseInt(txtId.getText());
        int quantity = Integer.parseInt(txtQuantity.getText());
        String name = txtName.getText();
        String model = txtModel.getText();
        Double cost = Double.valueOf(txtCost.getText());
        Double price = Double.valueOf(txtPrice.getText());
        
        HardwareComponent component = new HardwareComponent(id, quantity, cost, price, name, model);
    
        return component;
    }
    
    public void clearFields(){
        String voidString = "";
        int generatedId = HardwareComponentController.generateId();
        txtId.setText(String.valueOf(generatedId));
        txtQuantity.setText(voidString);
        txtName.setText(voidString);
        txtModel.setText(voidString);
        txtCost.setText(voidString);
        txtPrice.setText(voidString);
    }
    
    private void showPanel(JPanel panelUI) {
        panelUI.setSize(900, 675);
        panelUI.setLocation(0, 0);
        Content.removeAll();
        Content.add(panelUI, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    
    public void fillFields(HardwareComponent updatingComponent){
        String voidString = "";
        txtId.setText(String.valueOf(updatingComponent.getId()));
        txtQuantity.setText(String.valueOf(updatingComponent.getQuantity()));
        txtName.setText(updatingComponent.getName());
        txtModel.setText(updatingComponent.getModel());
        txtCost.setText(String.valueOf(updatingComponent.getCost()));
        txtPrice.setText(String.valueOf(updatingComponent.getPrice()));
    }
    
    public void clearFields(int idOfUpdating){
        String voidString = "";
        txtId.setText(String.valueOf(idOfUpdating));
        txtQuantity.setText(voidString);
        txtName.setText(voidString);
        txtModel.setText(voidString);
        txtCost.setText(voidString);
        txtPrice.setText(voidString);
    }
    

}
